name: Windows Build
on:
  push:
    branches: [ legacy/flixel ]
  workflow_dispatch:
jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@main
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
        
      - name: Installing/Updating libraries
        run: |
          haxelib --global --always install hmm
          haxelib run hmm install

          haxelib remove rulescript
          haxelib git rulescript https://github.com/Kriptel/RuleScript.git dev
          
          haxelib set lime git
      
      - name: Building HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../../

      - name: Building Lime
        run: |
          haxelib --always run lime rebuild windows

      - name: Building the game
        run: |
          haxelib --always run lime build windows -DDEV_BUILD
      
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Friday Again Garfie Baby
          path: export/release/windows/bin
      
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v3
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows